sudo: required
services:
  - docker

before_install:
  - docker build -t dre4success/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dre4success/react-test npm test -- --coverage

after_success:
  - docker build -t dre4success/multi-client ./client
  - docker build -t dre4success/multi-nginx ./nginx
  - docker build -t dre4success/multi-server ./server
  - docker build -t dre4success/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push dre4success/multi-client
  - docker push dre4success/multi-nginx
  - docker push dre4success/multi-server
  - docker push dre4success/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-428687659842
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY